workflow:
  rules:
    - if: '$CI_COMMIT_TAG'
      when: never
    - when: always

default:
  image: node:24-bookworm-slim
  tags:
    - linux-homelab-general-vm
  cache:
    key:
    files:
      - package-lock.json
    paths:
      - .npm/
      
variables:
  DOCKER_NAME: "cheulong/movies-finder-frontend"
  DOCKER_IMAGE: $CI_REGISTRY_IMAGE
  DOCKER_TAG: $CI_COMMIT_SHORT_SHA
  DOCKER_HOST: tcp://docker:2375
  DOCKER_TLS_CERTDIR: ""
  NPM_CONFIG_CACHE: "$CI_PROJECT_DIR/.npm"


.base_docker_job:
  image:
    name: docker:28
  services:
    - name: docker:dind
      alias: docker

.intall_dependencies:
  before_script:
    - npm ci --ignore-scripts --prefer-offline


stages:
  # - prepare
  - sast_scan
  - test
  # - build
  # - security
  # - dast_scan
  # - deploy
  # - release
  # - slack_notify
  # - clean_up